"""empty message

Revision ID: dfb47809984f
Revises: 07b8969ff79e
Create Date: 2017-03-13 05:07:25.853188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfb47809984f'
down_revision = '07b8969ff79e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profile', sa.Column('gender', sa.String(length=7), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profile', 'gender')
    # ### end Alembic commands ###
